# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153clFhpTpEgbDIZ4570DZizvHC4faBvs
"""

from google.colab import drive
drive.mount('/content/drive')

"""#Reading csv file data"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/project_files/winequality.csv')
print(df)

"""#Checking the first five data"""

print(df.head())

"""#Data information"""

df.info()

"""#Data description"""

df.describe()

"""#Checking null values if any"""

print(df.isnull().sum())

"""Implementing correlation for better data understanding"""

corr_matrix=df.corr()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,10))
sns.heatmap(corr_matrix,annot=True,cmap="coolwarm")
plt.show()

"""#Checking the quality correlation."""

quality_corr = corr_matrix["quality"].sort_values(ascending=False)

print(quality_corr)

df["quality_label"]=(df["quality"]>=7).astype(int)
print(df["quality_label"].head())

"""#Features and target value"""

X=df.drop(["quality","quality_label"],axis=1)
Y=df["quality_label"]
print(X.head())
print(Y.head())

"""#Train-test-split data"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)

"""#Training data through logistic regression(unscaled)"""

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,Y_train)
print("Model trained successfully through logistic regression")

"""Logistic regression prediction"""

l_prediction=model.predict(X_test)
print(l_prediction[:5])

"""Logistic regression metrics analysis"""

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
accuracy=accuracy_score(Y_test,l_prediction)
precision=precision_score(Y_test,l_prediction)
recall=recall_score(Y_test,l_prediction)
f1=f1_score(Y_test,l_prediction)
c_matrix=confusion_matrix(Y_test,l_prediction)

print("Accuracy:",accuracy)
print("Precision:",precision)
print("Recall:",recall)
print("F1 Score:",f1)
print("Confusion Matrix:")
print(c_matrix)

"""#Scaling data"""

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
print(X_train_scaled[:5])

"""#Traing data through logistic regression(scaled)"""

scaled_model=LogisticRegression()
scaled_model.fit(X_train_scaled,Y_train)
print("Model trained successfully through logistic regression with scaled value")

"""Prediction of scaled data"""

scaled_prediction=scaled_model.predict(X_test_scaled)
print(scaled_prediction[:5])

"""Metrics analysis for scaled value"""

S_accuracy=accuracy_score(Y_test,scaled_prediction)
S_precision=precision_score(Y_test,scaled_prediction)
S_recall=recall_score(Y_test,scaled_prediction)
S_f1=f1_score(Y_test,scaled_prediction)
S_c_matrix=confusion_matrix(Y_test,scaled_prediction)

print("Accuracy:",S_accuracy)
print("Precision:",S_precision)
print("Recall:",S_recall)
print("F1 Score:",S_f1)
print("Confusion Matrix:")
print(S_c_matrix)

"""Prediction for scaled trained value"""

scaled_predict=[[7.4, 0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51, 0.56,9.4]]
scaled_data=scaler.transform(scaled_predict)
print(scaled_model.predict(scaled_data))

"""Comparision between metrics values"""

comparison=pd.DataFrame({

    "Accuracy":[accuracy,S_accuracy],
    "Precision":[precision,S_precision],
    "Recall":[recall,S_recall],
    "F1 Score":[f1,S_f1]
})
print(comparison)

"""#Training data using KNN"""

from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled,Y_train)
print("Model trained successfully through KNN")

"""Prediction after trained from knn"""

knn_prediction=knn_model.predict(X_test_scaled)
print(knn_prediction)

"""Metrics analysis for knn value"""

k_accuracy=accuracy_score(Y_test,knn_prediction)
k_precision=precision_score(Y_test,knn_prediction)
k_recall=recall_score(Y_test,knn_prediction)
k_f1=f1_score(Y_test,knn_prediction)
k_c_matrix=confusion_matrix(Y_test,knn_prediction)

print("Accuracy:",k_accuracy)
print("Precision:",k_precision)
print("Recall:",k_recall)
print("F1 Score:",k_f1)
print("Confusion Matrix:")
print(k_c_matrix)

"""KNN prediction"""

k_predict=[[7.4, 0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51, 0.56,9.4]]
k_scaled_predict=scaler.transform(k_predict)
print(knn_model.predict(k_scaled_predict))

"""#Training data using DecisionTreeClassifier"""

from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier()
dt_model.fit(X_train,Y_train)
print("Model trained successfully through Decision Tree")

"""Decision tree trained data prediction"""

dt_prediction=dt_model.predict(X_test)
print(dt_prediction)

"""Metrics analysis for decision tree"""

d_accuracy=accuracy_score(Y_test,dt_prediction)
d_precision=precision_score(Y_test,dt_prediction)
d_recall=recall_score(Y_test,dt_prediction)
d_f1=f1_score(Y_test,dt_prediction)
d_c_matrix=confusion_matrix(Y_test,dt_prediction)
print("Accuracy:",d_accuracy)
print("Precision:",d_precision)
print("Recall:",d_recall)
print("F1 Score:",d_f1)
print("Confusion Matrix:")
print(d_c_matrix)

"""Decision tree trained model prediction"""

dt_predict=[[7.4, 0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51, 0.56,9.4]]
print(dt_model.predict(dt_predict))

"""#Models metrics comparision"""

all_models_data = {
    "Model": ["Logistic Regression (Scaled)", "Knn", "Decision Tree"],
    "Accuracy": [S_accuracy,k_accuracy,d_accuracy],
    "Precision": [S_precision, k_precision, d_precision],
    "Recall": [S_recall, k_recall, d_recall],
    "F1 Score": [S_f1, k_f1, d_f1]
}
comparison_df = pd.DataFrame(all_models_data)
print(comparison_df)

"""#Comparision graph"""

comparison_df.set_index("Model").plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Comparison of ML Models")
plt.ylabel("Score")
plt.show()

"""#Hyperparameters for best model among the models used"""

p_grid={
    "n_neighbors":[10,50,100],
    "weights":["uniform","distance"]
}

"""Grid Search CV"""

from sklearn.model_selection import GridSearchCV
grid_find=GridSearchCV(KNeighborsClassifier(),p_grid,cv=5)
grid_find.fit(X_train_scaled,Y_train)
print(grid_find.best_params_)

"""Training using best model"""

best_model=grid_find.best_estimator_
best_prediction=best_model.predict(X_test_scaled)
print(best_prediction[:5])

"""Best model accuracy analysis"""

print(accuracy_score(Y_test,best_prediction))

"""#Feature importance"""

from sklearn.inspection import permutation_importance
result=permutation_importance(best_model,X_test_scaled,Y_test,n_repeats=10,random_state=42)
print(result)

importances=pd.DataFrame({
    "Features":X.columns,
    "Importance":result.importances_mean})
importances=importances.sort_values("Importance",ascending=False)
print(importances)

"""#Prediction after best model training"""

fa=float(input("Enter fixed acidity: "))
va=float(input("Enter volatile acidity: "))
ca=float(input("Enter citric acid: "))
rs=float(input("Enter residual sugar: "))
cl=float(input("Enter chlorides: "))
fl=float(input("Enter free sulfur dioxide: "))
ts=float(input("Enter total sulfur dioxide: "))
d=float(input("Enter density: "))
ph=float(input("Enter pH: "))
s=float(input("Enter sulphates: "))
a=float(input("Enter alcohol: "))
print("Your product details are as follows:")
print("Fixed Acidity:",fa)
print("Volatile Acidity:",va)
print("Citric Acid:",ca)
print("Residual Sugar:",rs)
print("Chlorides:",cl)
print("Free Sulphur Dioxide:",fl)
print("Total Sulphur Dioxide:",ts)
print("Density:",d)
print("pH:",ph)
print("Sulphates:",s)
print("Alcohol:",a)
best_model_prediction=[[fa,va,ca,rs,cl,fl,ts,d,ph,s,a]]
if best_model.predict(best_model_prediction)==1:
  print("The quality of the wine is: Good")
else:
  print("The quality of the wine is: Bad")