# -*- coding: utf-8 -*-
"""Project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFkWTfV5g2E2BR1Jh3p3FaFz7qfvIDpf

#Importing file
"""

import pandas as pd
df=pd.read_csv('AI-Based Hiring Prediction System.csv')
print(df)

"""#Checking the directory list"""

import os
print(os.listdir())

"""#EDA"""

df.head()

df.describe()

df.info()

df.shape

print(df.isnull().sum())

df['Certifications'].head(10)

df['Certifications']=df['Certifications'].fillna('No certifications')

df.duplicated()

"""Feature Engineering"""

numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()
if "Resume_ID" in numerical_cols:
    numerical_cols.remove("Resume_ID")
print("Numerical Columns:")
print(numerical_cols)

print("\nCategorical Columns:")
print(categorical_cols)

df['Recruiter Decision'].value_counts()

"""Visualization of Data"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(9,5))
sns.countplot(data=df , x='Recruiter Decision')
plt.xlabel('Recruiter Decision')
plt.ylabel('Count')
plt.title('Recruiter Decision Distribution')
plt.show()

for col in numerical_cols:
    plt.figure(figsize=(7,4))

    sns.histplot(df[col], kde=True, bins=20)

    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")

    plt.show()

"""Correlation matrix"""

plt.figure(figsize=(8,6))

corr = df[numerical_cols].corr()

sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")

plt.title("Correlation Matrix")

plt.show()

"""Education field distribution"""

plt.figure(figsize=(9,5))
sns.countplot(data=df,x='Education',order=df['Education'].value_counts().index)
plt.xlabel('Education')
plt.ylabel('Count')
plt.title('Education Distribution')
plt.show()

"""Job Role distribution"""

plt.figure(figsize=(8,6))
sns.countplot(data=df, x='Job Role',order=df['Job Role'].value_counts().index)
plt.xlabel('Job Role')
plt.ylabel('Count')
plt.title('Job Role Distribution')
plt.show()

"""Certification Distribution"""

plt.figure(figsize=(10,5))
sns.countplot(data=df, x='Certifications',order=df['Certifications'].value_counts().index)
plt.xlabel('Certifications')
plt.ylabel('Count')
plt.title('Certification Distribution')
plt.show()

"""Checking outliers"""

# Remove Resume_ID if it's still in numerical_cols
if "Resume_ID" in numerical_cols:
    numerical_cols.remove("Resume_ID")

fig, axes = plt.subplots(2, 2, figsize=(14, 8))
axes = axes.flatten()

for i, col in enumerate(numerical_cols):
    sns.boxplot(x=df[col], ax=axes[i])
    axes[i].set_title(f"Boxplot of {col}")

plt.tight_layout()
plt.show()

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

"""Comparision of various fields with recruiter decision checking how each field affects the recruiter decision"""

plt.figure(figsize=(10,5))
sns.boxplot(data=df,x='Recruiter Decision',y='Experience (Years)')
plt.xlabel('Recruiter Decision')
plt.ylabel('Experience')
plt.title('Recruiter Decision vs Experience')
plt.show()

plt.figure(figsize=(10,5))
sns.boxplot(data=df,x='Recruiter Decision',y='AI Score (0-100)')
plt.xlabel('Recruiter Decision')
plt.ylabel('AI Score')
plt.title('Recruiter Decision vs AI Score')
plt.show()

plt.figure(figsize=(10,5))
sns.boxplot(data=df,x='Recruiter Decision',y='Projects Count')
plt.xlabel('Recruiter Decision')
plt.ylabel('Projects count')
plt.title('Recruiter Decision vs Projects count')
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Recruiter Decision",
    y="Salary Expectation ($)"
)

plt.title("Salary Expectation vs Recruiter Decision")
plt.show()

plt.figure(figsize=(10,5))

sns.countplot(data=df,x="Education",hue="Recruiter Decision")

plt.title("Education vs Recruiter Decision")
plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(10,5))

sns.countplot(data=df,x="Job Role",hue="Recruiter Decision")

plt.title("Job Role vs Recruiter Decision")
plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(12,5))

top_certifications = df["Certifications"].value_counts().head(10).index

sns.countplot(
    data=df[df["Certifications"].isin(top_certifications)],
    x="Certifications",
    hue="Recruiter Decision"
)

plt.title("Top Certifications vs Recruiter Decision")
plt.xticks(rotation=45)

plt.show()

"""##Working with data including AI_score

#Data preprocessing with AI-SCORE
"""

df=df.drop(columns=['Resume_ID','Name'])

"""Feature and target value selection"""

X=df.drop(columns=['Recruiter Decision'],axis=1)
y=df['Recruiter Decision']
print(X.dtypes)

"""Encoding target value"""

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

X = X.drop(columns=["Skills"])

"""One hot encoding"""

X=pd.get_dummies(X , columns=["Education", "Certifications", "Job Role"],drop_first=True)
print(X.head())

"""Train test split data"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

"""Standard scaling the features"""

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[numerical_cols]=sc.fit_transform(X_train[numerical_cols])
X_test[numerical_cols]=sc.transform(X_test[numerical_cols])

print(X_train.columns.tolist())

"""#Model Training with AI score included"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score,classification_report,confusion_matrix,ConfusionMatrixDisplay)
print("Model training necessary data imported")

"""Logistic Regression"""

lg=LogisticRegression()
lg.fit(X_train,y_train)
y_pred_lr=lg.predict(X_test)
print(accuracy_score(y_test,y_pred_lr))
print(classification_report(y_test,y_pred_lr))
cm = confusion_matrix(y_test, y_pred_lr)

ConfusionMatrixDisplay(cm).plot()
plt.show()

"""Decision tree"""

dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred_dt=dt.predict(X_test)
print(accuracy_score(y_test,y_pred_dt))
print(classification_report(y_test,y_pred_dt))
cm = confusion_matrix(y_test, y_pred_dt)

ConfusionMatrixDisplay(cm).plot()
plt.show()

"""Random forest"""

rf=RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred_rf=rf.predict(X_test)
print(accuracy_score(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))
cm = confusion_matrix(y_test, y_pred_rf)

ConfusionMatrixDisplay(cm).plot()
plt.show()

"""Gradient Boosting"""

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    random_state=42
)

gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

print("Accuracy:",
      accuracy_score(y_test, y_pred_gb))
print(classification_report(y_test,y_pred_gb))
cm = confusion_matrix(y_test, y_pred_gb)

ConfusionMatrixDisplay(cm).plot()
plt.show()

"""xgboost"""

!pip install xgboost

from xgboost import XGBClassifier
xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)
print("Accuracy:",accuracy_score(y_test, y_pred_xgb))
print(classification_report(y_test,y_pred_xgb))
cm = confusion_matrix(y_test, y_pred_xgb)

ConfusionMatrixDisplay(cm).plot()
plt.show()

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_gb),
        accuracy_score(y_test, y_pred_xgb)
    ]
})

results.sort_values(
    by="Accuracy",
    ascending=False
)

feature_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf.feature_importances_})

feature_importance = feature_importance.sort_values(by="Importance",ascending=False)

print(feature_importance.head(10))

plt.figure(figsize=(10,6))

plt.barh(
    feature_importance["Feature"][:10],feature_importance["Importance"][:10])

plt.title("Top 10 Important Features")
plt.xlabel("Importance")

plt.gca().invert_yaxis()
plt.show()

"""#Hyperparameter tuning"""

from sklearn.model_selection import GridSearchCV

# Create the model
rf = RandomForestClassifier(random_state=42)

# Parameters to test
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

# Grid Search
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy'
)

# Train
grid_search.fit(X_train, y_train)

# Best parameters
print("Best Parameters:")
print(grid_search.best_params_)

# Best score
print("\nBest Cross Validation Accuracy:")
print(grid_search.best_score_)

best_rf = grid_search.best_estimator_
y_pred_best_rf = best_rf.predict(X_test)
print("Accuracy:",accuracy_score(y_test, y_pred_best_rf))
print(classification_report(y_test,y_pred_best_rf))
cm = confusion_matrix(y_test, y_pred_best_rf)

ConfusionMatrixDisplay(cm).plot()
plt.show()

"""Prediction"""

new_candidate = pd.DataFrame({
    "Experience (Years)": [5],
    "Salary Expectation ($)": [80000],
    "Projects Count": [7],
    "AI Score (0-100)": [90],
    "Education_B.Tech": [1],
    "Education_M.Tech": [0],
    "Education_MBA": [0],
    "Education_PhD": [0],
    "Certifications_Deep Learning Specialization": [1],
    "Certifications_Google ML": [0],
    "Certifications_No certifications": [0],
    "Job Role_Cybersecurity Analyst": [0],
    "Job Role_Data Scientist": [1],
    "Job Role_Software Engineer": [0]
})
numerical_features = [
    "Experience (Years)",
    "Salary Expectation ($)",
    "Projects Count",
    "AI Score (0-100)"
]
new_candidate[numerical_features] = sc.transform(
    new_candidate[numerical_features]
)
prediction = best_rf.predict(new_candidate)

print("Prediction:", le.inverse_transform(prediction)[0])

"""##Working with data without including AI_Score

Data preprocessing without ai_score
"""

X1 = df.drop(["Recruiter Decision", "AI Score (0-100)"], axis=1)
y1 = df["Recruiter Decision"]

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y1 = label_encoder.fit_transform(y1)

X1 = pd.get_dummies(
    X1,
    columns=["Education", "Certifications", "Job Role"],
    drop_first=True
)

X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1,
    y1,
    test_size=0.2,
    random_state=42,
    stratify=y1
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_features = [
    "Experience (Years)",
    "Salary Expectation ($)",
    "Projects Count"
]

X1_train[numerical_features] = scaler.fit_transform(
    X1_train[numerical_features]
)

X1_test[numerical_features] = scaler.transform(
    X1_test[numerical_features]
)

"""#Model training removing AI_Score

Logistic regression
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Drop 'Skills' column if it exists in X1_train and X1_test
if 'Skills' in X1_train.columns:
    X1_train = X1_train.drop(columns=['Skills'])
if 'Skills' in X1_test.columns:
    X1_test = X1_test.drop(columns=['Skills'])

lr1 = LogisticRegression(random_state=42)

lr1.fit(X1_train, y1_train)

y1_pred_lr = lr1.predict(X1_test)
print("Accuracy:", accuracy_score(y1_test, y1_pred_lr))

"""Decision tree"""

from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier(random_state=42)
dt1.fit(X1_train, y1_train)
y1_pred_dt = dt1.predict(X1_test)
print("Accuracy:", accuracy_score(y1_test, y1_pred_dt))

"""Random forest"""

from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier(random_state=42)
rf1.fit(X1_train, y1_train)
y1_pred_rf = rf1.predict(X1_test)
print("Accuracy:", accuracy_score(y1_test, y1_pred_rf))

"""Gradient boosting"""

from sklearn.ensemble import GradientBoostingClassifier
gb1 = GradientBoostingClassifier(random_state=42)
gb1.fit(X1_train, y1_train)
y1_pred_gb = gb1.predict(X1_test)
print("Accuracy:", accuracy_score(y1_test, y1_pred_gb))

"""XGBoost"""

from xgboost import XGBClassifier
xgb1 = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)
xgb1.fit(X1_train, y1_train)
y1_pred_xgb = xgb1.predict(X1_test)
print("Accuracy:", accuracy_score(y1_test, y1_pred_xgb))

"""Models comperision"""

import pandas as pd

results1 = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_score(y1_test, y1_pred_lr),
        accuracy_score(y1_test, y1_pred_dt),
        accuracy_score(y1_test, y1_pred_rf),
        accuracy_score(y1_test, y1_pred_gb),
        accuracy_score(y1_test, y1_pred_xgb)
    ]
})

results1.sort_values(by="Accuracy", ascending=False)

import pandas as pd

new_candidate = pd.DataFrame({
    "Experience (Years)": [5],
    "Salary Expectation ($)": [70000],
    "Projects Count": [6],

    "Education_B.Tech": [1],
    "Education_M.Tech": [0],
    "Education_MBA": [0],
    "Education_PhD": [0],

    "Certifications_Deep Learning Specialization": [1],
    "Certifications_Google ML": [0],
    "Certifications_No certifications": [0],

    "Job Role_Cybersecurity Analyst": [0],
    "Job Role_Data Scientist": [1],
    "Job Role_Software Engineer": [0]
})
numerical_features = [
    "Experience (Years)",
    "Salary Expectation ($)",
    "Projects Count"
]

new_candidate[numerical_features] = scaler.transform(
    new_candidate[numerical_features]
)
prediction = rf1.predict(new_candidate)

print("Prediction:", label_encoder.inverse_transform(prediction)[0])

import joblib

# Save the model
joblib.dump(xgb1, "hiring_prediction_model.pkl")

# Save the scaler
joblib.dump(scaler, "scaler.pkl")

# Save the label encoder
joblib.dump(label_encoder, "label_encoder.pkl")

print("Model, Scaler, and Label Encoder saved successfully!")